/* Author: Sotiris Konstantis */

enum ExtremeWeather {
  EXTREME_WEATHER,
  HEAVY_THUNDERSTORMS,
  EXTREMELY_HIGH_TEMPERATURES,
  EXTREMELY_LOW_TEMPERATURES,
  STRONG_WINDS,
  HEAVY_SNOW,
  EXTREME_WEATHER_CURFEW,
}

export default ExtremeWeather;